# Generated by Django 4.2.15 on 2024-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=512)),
                ('district', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=3000)),
                ('location_image', models.ImageField(blank=True, default='locations/locations.jpg', null=True, upload_to='locations/')),
            ],
        ),
    ]
