# Generated by Django 4.2.15 on 2024-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, default='universities/london.png', null=True, upload_to='universities/')),
            ],
        ),
    ]
