# Generated by Django 4.2.15 on 2024-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(default='London', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='UK', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, default='universities/default-service.jpg', null=True, upload_to='universities/'),
        ),
    ]
