# Generated by Django 4.2.15 on 2024-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='Requirement1',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement2',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement3',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement4',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement5',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement6',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='Requirement7',
            field=models.CharField(blank=True, choices=[('Consolidated Marksheets', 'Consolidated Marksheets'), ('Letter of Reference', 'Letter Of Reference'), ('Personal Statement', 'Personal Statement'), ('Semester Marksheets', 'Semester Marksheetsn'), ('Passport', 'Passport'), ('Provisional Certificate', 'Provisional Certificate'), ('I20', 'I20')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='about',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
